### ISSUE TITLE
Food Trucks & Pre Order Menu- Mobile: Please align the Post Title and Post Description to the left just like the design and desktop view layout

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#102]
Devices:
Ipad (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/12707669/37e93572-c8d2-11e5-89d5-05228494e076.png)

Itouch & S4 (portrait & landscape)

**Comment by roseliesromeo** [comment]
No change made.
