### ISSUE TITLE
News: Please align the Post Title to the left just like the design and desktop view layout 

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#103]
Devices:
S4 & Itouch5 (portrait & landscape)
Ipad (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/12707712/8ed1852e-c8d2-11e5-802b-e8e66d131318.png)

**Comment by roseliesromeo** [comment]
Alignment in iPad is left while the rest of the mobile devices, post title is centered.
