### ISSUE TITLE
Total Page Size: Didn't pass - 2MB is the maximum, currently it is 3.12 mb. Please see link below for the GT Metrix result

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#109]
https://gtmetrix.com/reports/jds-fastfood.stage.titanweb.com.au/9JrwSC4P

**Comment by ravititan** [comment]
https://gtmetrix.com/reports/jds-fastfood.stage.titanweb.com.au/eNXlyFN4
