### ISSUE TITLE
Social Media - Bottom Area: Not properly styled, both ends not equal and the 2nd one has not yet done coz it was cut at the top

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#29]
![image](https://cloud.githubusercontent.com/assets/13363508/12284595/d0b60d52-b9eb-11e5-9835-44f2e38a467a.png)

**Comment by ravititan** [comment]
Waiting for the app review : https://projects.titanweb.com.au/public/index.php?path_info=projects/jds-fast-food-pack2/tasks/27

**Comment by maehtitan** [comment]
I will remove for the moment the Fixed label until this one is completely

**Comment by roseliesromeo** [comment]
Any update on this one @ravititan?

**Comment by ravititan** [comment]
Did not got any update on this.
https://projects.titanweb.com.au/public/index.php?path_info=projects%2Fjds-fast-food-pack2%2Ftasks%2F27

**Comment by ravititan** [comment]
@maehtitan : This issue has been fixed but we are keeping the social feed in the center as the social feed cannot exceed the of width of 500px, It has maximum width of 500px;
