### ISSUE TITLE
Pre-footer: Is it completely removed or not? Coz it is still existing from the project scope. Kindly make an update if it was totally removed from the implementation

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#31]
![image](https://cloud.githubusercontent.com/assets/13363508/12285865/b874d4d6-b9f9-11e5-841d-2e7f265ee870.png)

**Comment by ravititan** [comment]
Prefooter has been removed due to change in design ,project scope has been updated.
