### ISSUE TITLE
News, News Single View - Mobile: The Social media at the bottom doesn't styled properly

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#86]
Devices:
Ipad (portrait)
S4 & Itouch (portrait & lanscape)
![image](https://cloud.githubusercontent.com/assets/13363508/12474885/84708e8a-c059-11e5-959c-5d1aba629be2.png)

**Comment by maehtitan** [comment]
Fixed in ipad portrait but affected issue found in landscape view

**Comment by maehtitan** [comment]
No changes has been made, still the same

**Comment by roseliesromeo** [comment]
Sidebar items don't have the same width.

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/12744770/047af964-c9d1-11e5-811e-837e2ab1e862.png)

**Comment by maehtitan** [comment]
Issues still recurring.
Steps to replicate:
Step 1: Click the News page in Ipad portrait view
Step 2: Change the Orientation to landscape view
Step 3: Image will overflow the layout, please see screenshot below
![image](https://cloud.githubusercontent.com/assets/13363508/12804658/f4a19a9c-cb2f-11e5-9e68-2dca05ca3be4.png)


Steps to replicate:
Step 1: Click the News page in Ipad landscape view
Step 2: Change the Orientation to portrait view
Step 3: Facebook width doesn't fit the layout, please see screenshot below
![image](https://cloud.githubusercontent.com/assets/13363508/12804663/001118e4-cb30-11e5-8bed-293a4ecf24ad.png)

**Comment by ravititan** [comment]
@maehtitan : it is fixed now.
