### ISSUE TITLE
Upcoming & Previous events Listing view: Columns are not consistent and its alignment, some are 2 and some are 1, some are left aligned and some are center aligned

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#88]
![image](https://cloud.githubusercontent.com/assets/13363508/12475335/40593842-c05d-11e5-9aac-348eada8619a.png)
![image](https://cloud.githubusercontent.com/assets/13363508/12475398/b021273e-c05d-11e5-9701-2618f3cf4305.png)

**Comment by maehtitan** [comment]
Still not yet fixed
![image](https://cloud.githubusercontent.com/assets/13363508/12574097/b3178046-c43b-11e5-8e79-6a2a3968092e.png)

**Comment by maehtitan** [comment]
Please implement the iPad portrait view view just like the iPad landscape view or the desktop view, coz currently a lot of space wasted on the right side
![image](https://cloud.githubusercontent.com/assets/13363508/12670850/9eed2982-c6a6-11e5-8652-419e960eee2b.png)

**Comment by roseliesromeo** [comment]
Please make sure that you don't just change the label to fixed.  Please fix the issue.

**Comment by maehtitan** [comment]
Please apply fix in the food trucks page
![image](https://cloud.githubusercontent.com/assets/13363508/12771189/38faee92-ca62-11e5-906a-a8443ebb2485.png)
