### ISSUE TITLE
Homepage - Social Media Feed - Mobile: Alignment are not equal, facebook is left aligned and IG layout is right aligned

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#92]
Devices:
S4 (portrait & landscape)
Itouch5 (portrait & landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/12574523/662bfe02-c43f-11e5-9d95-499b3ac0a34f.png)

Looks like this in ipad (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/12574566/e645b1fa-c43f-11e5-8207-90fc71bc3ebb.png)

**Comment by maehtitan** [comment]
Not yet fixed, 
Ipad 
![image](https://cloud.githubusercontent.com/assets/13363508/12670930/3268f358-c6a7-11e5-98bd-372142a057a7.png)
Itouch & S4 (portrait)
![image](https://cloud.githubusercontent.com/assets/13363508/12671052/0f2f8ad6-c6a8-11e5-9533-15dbeb01db7b.png)
Itouch & S4 (landscape)
![image](https://cloud.githubusercontent.com/assets/13363508/12671071/36a36790-c6a8-11e5-80bf-fefe2267d91e.png)

**Comment by ravititan** [comment]
The Facebook plugin that has been used in the site has a max width of 500px and we cannot overwrite the style of the Facebook plugin as the style are from remote files and it is not allowing us to overwrite the styles
![facebook-page-plugin](https://cloud.githubusercontent.com/assets/13450891/12718007/a7a647a8-c911-11e5-9e7e-20e96f0e5ca8.jpg)
.

**Comment by maehtitan** [comment]
All screenshots reported from the top all the way down not yet fixed

**Comment by ravititan** [comment]
@maehtitan : This issue has been fixed but we are keeping the social feed in the center as the social feed cannot exceed the of width of 500px, It has maximum width of 500px;
