### ISSUE TITLE
Events - Upcoming events single view: There shouldn't be carousel implemented since it is not mentioned in the scope, please kindly remove

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/JDs-Fast-Food#93]
![image](https://cloud.githubusercontent.com/assets/13363508/12574693/24331010-c441-11e5-951f-b0422aac3910.png)

**Comment by ravititan** [comment]
Need to discuss with Salman

**Comment by ravititan** [comment]
The project scope has been updated.
